server:
  port: 9000
spring:
   kafka:
     producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        bootstrap-servers: 3000
third:
  party:
    api:
      url: https://lookup.binlist.net
logging:
  level:
    root: INFO